/*	Able Interpreter Resource Id's */

#ifndef	ABLEINT_RES_IDS
#define ABLEINT_RES_IDS

#define	INTERPRETER_RES_ID_BASE				(INTERPRETER<<8)

// Alerts
#define NEED_W0_IMAGE_FIRST_ALERT_ID		(INTERPRETER_RES_ID_BASE+0 )
#define NEED_W0_IMAGE_UPDATE_ALERT_ID		(INTERPRETER_RES_ID_BASE+1 )
#define COULD_NOT_FIND_WINBOOT				(INTERPRETER_RES_ID_BASE+2 )
#define LIKELY_OUT_OF_MEMORY				(INTERPRETER_RES_ID_BASE+3 )
#define NEED_UPDATED_EDITVIEW				(INTERPRETER_RES_ID_BASE+4 )
#define	SETTINGS_DIALOG_ID					(INTERPRETER_RES_ID_BASE+5 )
#define	NEED_TO_RELAUNCH_ID					(INTERPRETER_RES_ID_BASE+6 )
#define	PCI1_IN_USE_ALERT					(INTERPRETER_RES_ID_BASE+7 )
#define NEED_TO_CALIBRATE_ALERT				(INTERPRETER_RES_ID_BASE+8 )
#define WANT_TO_CALIBRATE_ALERT				(INTERPRETER_RES_ID_BASE+9 )
#define WANT_TO_CALIBRATE_ALERT_NOD3		(INTERPRETER_RES_ID_BASE+10)
#define	CACHE_UPDATE_NEEDED_ID				(INTERPRETER_RES_ID_BASE+11)
#define	W0_FILE_IS_MISSING					(INTERPRETER_RES_ID_BASE+12)

// Menus
#define	CABLE_LENGTH_MENU_ID				(INTERPRETER_RES_ID_BASE+0)
#define	BUS_LOADING_MENU_ID					(INTERPRETER_RES_ID_BASE+1)
#define	NET_VISIBLE_MENU_ID					(INTERPRETER_RES_ID_BASE+2)
#define	USE_MP_MENU_ID						(INTERPRETER_RES_ID_BASE+3)
#define	USE_MP_NO_MP_ID						(INTERPRETER_RES_ID_BASE+4)
#define	M512K_MENU_ID						(INTERPRETER_RES_ID_BASE+5)
#define	POLY_MENU_ID						(INTERPRETER_RES_ID_BASE+6)


// Icons
#define	SETTINGS_DIALOG_ICON_64				(INTERPRETER_RES_ID_BASE+0)

#endif
